export const randomComments = [
  "Great work, keep it up!",
  "This is incredibly well-done.",
  "You're a fantastic writer!",
  "I'm inspired by your creativity.",
  "Absolutely brilliant!",
  "You have a unique perspective.",
  "Well articulated!",
  "I'm impressed by your talent.",
  "This is top-notch quality.",
  "You've outdone yourself!",
  "I'm amazed by your skills.",
  "You have a gift for this.",
  "I'm captivated by your work.",
  "Exceptional job!",
  "This is truly outstanding.",
  "You're making a positive impact.",
  "I'm grateful for your contribution.",
  "You're on the right track!",
  "I'm in awe of your abilities.",
  "You're raising the bar!",
];